services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdocs
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init_clean.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - app-network  # เชื่อมโยงกับ app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - app-network  # เชื่อมโยงกับ app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: userdocs
    networks:
      - app-network  # เชื่อมโยงกับ app-network
    volumes:
      - .uploads:/app/uploads
    command: >
      sh -c "npm run start"

volumes:
  mysql-data:  # Volume สำหรับข้อมูลของ MySQL

networks:
  app-network:  # ประกาศเครือข่าย app-network
    driver: bridge  # ใช้ driver แบบ bridge
