services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userdocs
    volumes:
<<<<<<< HEAD
      - mysql-data:/var/lib/mysql
      - ./init_clean.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: userdocs
    networks:
      - app-network
    command: >
      sh -c "npm run start"

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
=======
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
>>>>>>> 08a152116b602b401b653f49834f356bec910bd6
