services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_userdocs
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sa123456!
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql