version: '3.9'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_userdocs
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sa123456789
    ports:
      - "1433:1433"
    volumes:
      - ./init_clean.sql:/docker-entrypoint-initdb.d/init.sql
